name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Python Dependency Installation
      uses: py-actions/py-dependency-install@v4.0.0

    # - name: Run tests for data sanity
    #   run: make test
